# Generated by Django 4.1.7 on 2023-03-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_ministryname_image_ourhistory_image_vision_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_image', models.ImageField(upload_to='media')),
                ('member_title', models.CharField(max_length=200)),
                ('member_name', models.CharField(max_length=200)),
                ('member_biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tdaccf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TDACCF', models.TextField(default='')),
                ('image', models.FileField(default='', upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='OurStaffs',
        ),
    ]
