# Generated by Django 4.1.7 on 2024-02-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_testimonials_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosermons',
            name='video',
        ),
        migrations.AddField(
            model_name='videosermons',
            name='youtube_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='videosermons',
            name='caption',
            field=models.CharField(max_length=500),
        ),
    ]
