# Generated by Django 4.1.7 on 2024-02-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_remove_videosermons_video_videosermons_youtube_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosermons',
            name='coverphoto',
        ),
        migrations.RemoveField(
            model_name='videosermons',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='videosermons',
            name='youtube_video_ID',
            field=models.CharField(default='', max_length=500),
        ),
    ]
