# Generated by Django 4.1.7 on 2024-02-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_videosermons_coverphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosermons',
            name='youtube_video_ID',
        ),
        migrations.AddField(
            model_name='videosermons',
            name='youtube_url',
            field=models.URLField(default=''),
        ),
    ]
